https://www.perplexity.ai/search/b99dd1ac-2d40-4f7d-ba29-2972671abf18

In [10]:
import numpy as np

np.random.seed(1)
scores = np.random.randint(50, 101, size=(50, 5))
scores

array([[ 87,  93,  62,  58,  59],
       [ 61,  55,  65,  50,  66],
       [ 51,  62,  57,  95,  56],
       [ 75, 100,  70,  87,  68],
       [ 70,  61,  92,  78,  79],
       [ 64, 100,  54,  73,  73],
       [ 91,  99,  80,  82,  72],
       [ 63,  91,  59,  57,  72],
       [ 51,  50,  67,  58,  74],
       [ 63,  97,  92,  58,  80],
       [ 57,  53,  56,  71,  99],
       [ 53,  54,  74,  99,  93],
       [ 62,  76,  66,  95,  91],
       [ 68,  65,  50,  54,  75],
       [ 97,  84,  73,  57,  76],
       [ 75,  90,  72,  59,  53],
       [ 89,  73,  86,  77,  87],
       [ 69,  88,  58,  82,  84],
       [ 60,  73,  65,  97,  73],
       [ 75,  57,  78,  60,  96],
       [ 82,  74,  73,  51,  99],
       [ 63,  53,  50,  63,  56],
       [ 71,  56,  52,  62,  77],
       [ 71,  61,  57,  63,  58],
       [ 61,  62,  93,  70,  80],
       [ 86,  89,  57,  95,  54],
       [ 98,  68,  82,  63,  60],
       [ 73,  67,  57,  74,  60],
       [ 78,  70,  82,  62,  51],
       [ 80,  91,  74,  68,  83],
       [ 52,  94,  78,  89,  84],
       [ 60,  82,  91,  68,  72],
       [ 56,  52,  57,  89,  98],
       [ 65,  55,  67,  92,  70],
       [ 98,  72,  87,  63,  99],
       [100,  83,  70,  60,  82],
       [ 75,  71,  89,  82,  69],
       [ 75,  99,  64,  63,  70],
       [ 93,  56,  63,  65,  74],
       [ 59,  52,  57,  55,  86],
       [ 87,  71,  90,  63,  77],
       [ 99,  99,  97,  63,  90],
       [ 64,  95,  73,  66,  78],
       [ 92,  95,  53,  52,  64],
       [ 96,  50,  79,  61,  85],
       [ 79,  83,  52,  70,  69],
       [ 98,  82,  78,  68,  81],
       [ 78,  80,  60,  58,  95],
       [ 85,  82,  58,  70,  63],
       [100,  65,  91,  50,  94]], dtype=int32)

### 設定隨機種子

設定 NumPy 隨機種子的方法是使用 `np.random.seed()`，並傳入一個整數作為種子值。這樣每次執行程式時，隨機數生成器都會從相同的起點開始，產生相同的隨機數序列。

範例如下：

```python
import numpy as np

np.random.seed(123)  # 設定隨機種子為123
scores = np.random.randint(50, 101, size=(50, 5))
print(scores)
```
總結：   
- 使用 `np.random.seed(整數)` 設定隨機種子
- 種子數值可自行設定，通常為任意整數
- 設定後，隨機數生成可重現，適合測試和除錯用途

In [ ]:
import pandas as pd

df = pd.DataFrame(scores, columns=["國文", "英文", "數學", "生物", "物理"], index=[f"學生{x}" for x in range(1, 51)])

type(df) 
#傳出: pandas.core.frame.DataFrame
#是DataFrame的實體

df

       國文   英文  數學  生物  物理
學生1    87   93  62  58  59
學生2    61   55  65  50  66
學生3    51   62  57  95  56
學生4    75  100  70  87  68
學生5    70   61  92  78  79
學生6    64  100  54  73  73
學生7    91   99  80  82  72
學生8    63   91  59  57  72
學生9    51   50  67  58  74
學生10   63   97  92  58  80
學生11   57   53  56  71  99
學生12   53   54  74  99  93
學生13   62   76  66  95  91
學生14   68   65  50  54  75
學生15   97   84  73  57  76
學生16   75   90  72  59  53
學生17   89   73  86  77  87
學生18   69   88  58  82  84
學生19   60   73  65  97  73
學生20   75   57  78  60  96
學生21   82   74  73  51  99
學生22   63   53  50  63  56
學生23   71   56  52  62  77
學生24   71   61  57  63  58
學生25   61   62  93  70  80
學生26   86   89  57  95  54
學生27   98   68  82  63  60
學生28   73   67  57  74  60
學生29   78   70  82  62  51
學生30   80   91  74  68  83
學生31   52   94  78  89  84
學生32   60   82  91  68  72
學生33   56   52  57  89  98
學生34   65   55  67  92  70
學生35   98   72  87  63  99
學生36  100   83  70  60  82
學生37   75   71  89  82  69
學生38   75   99  64  63  70
學生39   93   56  63  65  74
學生40   59   52  57  55  86
學生41   87   71  90  63  77
學生42   99   99  97  63  90
學生43   64   95  73  66  78
學生44   92   95  53  52  64
學生45   96   50  79  61  85
學生46   79   83  52  70  69
學生47   98   82  78  68  81
學生48   78   80  60  58  95
學生49   85   82  58  70  63
學生50  100   65  91  50  94

In [ ]:
[x**2 for x in range(10) if x < 4]

[0, 1, 4, 9]

In [19]:
df.columns.name = "科目"
df.index.name = "姓名"
df

科目     國文   英文  數學  生物  物理
姓名
學生1    87   93  62  58  59
學生2    61   55  65  50  66
學生3    51   62  57  95  56
學生4    75  100  70  87  68
學生5    70   61  92  78  79
學生6    64  100  54  73  73
學生7    91   99  80  82  72
學生8    63   91  59  57  72
學生9    51   50  67  58  74
學生10   63   97  92  58  80
學生11   57   53  56  71  99
學生12   53   54  74  99  93
學生13   62   76  66  95  91
學生14   68   65  50  54  75
學生15   97   84  73  57  76
學生16   75   90  72  59  53
學生17   89   73  86  77  87
學生18   69   88  58  82  84
學生19   60   73  65  97  73
學生20   75   57  78  60  96
學生21   82   74  73  51  99
學生22   63   53  50  63  56
學生23   71   56  52  62  77
學生24   71   61  57  63  58
學生25   61   62  93  70  80
學生26   86   89  57  95  54
學生27   98   68  82  63  60
學生28   73   67  57  74  60
學生29   78   70  82  62  51
學生30   80   91  74  68  83
學生31   52   94  78  89  84
學生32   60   82  91  68  72
學生33   56   52  57  89  98
學生34   65   55  67  92  70
學生35   98   72  87  63  99
學生36  100   83  70  60  82
學生37   75   71  89  82  69
學生38   75   99  64  63  70
學生39   93   56  63  65  74
學生40   59   52  57  55  86
學生41   87   71  90  63  77
學生42   99   99  97  63  90
學生43   64   95  73  66  78
學生44   92   95  53  52  64
學生45   96   50  79  61  85
學生46   79   83  52  70  69
學生47   98   82  78  68  81
學生48   78   80  60  58  95
學生49   85   82  58  70  63
學生50  100   65  91  50  94